# Generated by Django 3.2.3 on 2022-02-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teams',
            new_name='team',
        ),
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
        migrations.AlterModelTable(
            name='team',
            table='Team',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
