# Generated by Django 3.2.3 on 2022-02-22 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220222_0659'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='team',
            new_name='teams',
        ),
        migrations.RenameModel(
            old_name='user',
            new_name='users',
        ),
        migrations.AlterModelTable(
            name='teams',
            table='Teams',
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
